---
title: "Georeferencing in Q"
author: "Sam Levin"
date: "5/6/2019"
output: pdf_document
---


1. Load in the TIFF from the first sampling in the Layers panel. This will allow you to find reference points to snap the new TIFF to.

2. Open plugin manager (_Plugins_ -> _Manage and Install Plugins..._)

3. Start typing "Georeferencer GDAL" into the search bar

4. Once you see "Georeferencer GDAL" appear in the menu, check the box next to it. Close the dialogue box

5. Select the _Raster_ dropdown and open the Georeferencer plugin

6. Click the _Add Raster_ button (top left corner) and select the TIFF from the current year

7. In the settings menu, select _Thin Plate Splines_ from the Transformation dropdown.

    + Also experimenting with Helmert transformations.

8. Make a name for the output layer. This should be the site name, the year, and the georeferencing method used (e.g. TPS, Helmert, etc).

9. Find pixels that are clearly in both TIFFs, and mark it the georeferencer.

10. A popup dialogue will appear, select the Find in Map Canvas option, and click the corresponding point on the previous year's TIFF. 

11. Repeat 9 and 10 as many times as possible.

12. Once you have created all of the georeferencing points, save them by going to _File_ -> _Save GCPs as..._.
    
    + There is now a GCPs folder in the *PhD_Processed_Data/* subfolder. If the country/site does not already have its own folder, create one.
    
    + The naming convention for GCPs is *site_Year1_Year2.points*. Saving these means others can check our work or extend the work on their own.
    


